---
# tasks file for mytomcatrole
- include_tasks: installjava.yml
- include_tasks: tomcatuser.yml
- include_tasks: installtomcat.yml
- include_tasks: updatepermission.yml
- include_tasks: createsystem.yml
- include_tasks: starttomcat.yml
- include_tasks: tomcatwebmanager.yml
- include_tasks: deployjenkins.yml
- include_tasks: restarttomcat.yml
